/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_democracy_electoral_court_infrastructure_jni_CedulaJni */

#ifndef _Included_com_democracy_electoral_court_infrastructure_jni_CedulaJni
#define _Included_com_democracy_electoral_court_infrastructure_jni_CedulaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_democracy_electoral_court_infrastructure_jni_CedulaJni
 * Method:    controloCedula
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_democracy_electoral_1court_infrastructure_jni_CedulaJni_controloCedula
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
