server:
  port: 8082
spring:
  application:
    name: ApiGateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: Products
        uri: lb://PRODUCTS
        predicates:
          - Path=/products/**
      routes[1]:
        id: accountancy
        uri: lb://ACCOUNTANCY
        predicates:
          - Path=/accountancy/**
      routes[2]:
        id: HumanResources
        uri: lb://HUMANRESOURCES
        predicates:
          - Path=/humanresources/**
      routes[3]:
        id: electoralcourt
        uri: lb://ELECTORALCOURT
        predicates:
          - Path=/electoralcourt/**
      routes[4]:
        id: SatateMachine
        uri: lb://STATEMACHINE
        predicates:
          - Path=/statemachine/**
      routes[5]:
        id: feing-client
        uri: lb://FEING-CLIENT
        predicates:
          - Path=/feingclient/**
      routes[6]:
        id: feing-target
        uri: lb://FEING-TARGET
        predicates:
          - Path=/feingtarget/**
      routes[7]:
        id: HelloServer
        uri: lb://HELLOSERVER
        predicates:
          - Path=/server/**
      routes[8]:
        id: HelloClient
        uri: lb://HELLOCLIENT
        predicates:
          - Path=/client/**
      default-filters: TokenRelay
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/democracy_realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/democracy_realm
        registration:
          spring-cloud-gateway-client:
            client-id: democracy_client
            client-secret: YYcdVQO1lB9F5IjxjN6ljHueBWhZz1aZ
            scope: openid
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:4200/*
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

