/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_com_delibolis_products_jni_JniExample */

#ifndef _Included_co_com_delibolis_products_jni_JniExample
#define _Included_co_com_delibolis_products_jni_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_com_delibolis_products_jni_JniExample
 * Method:    controloCedula
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_co_com_delibolis_products_jni_JniExample_controloCedula
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
