package com.democracy.person.service;

import com.democracy.person.domain.ChallengeAttempt;
import com.democracy.person.domain.User;
import com.democracy.person.dto.ChallengeAttemptDTO;
import com.democracy.person.mybatis.mappers.ChallengeAttemptMapper;
import com.democracy.person.mybatis.mappers.UserMapper;
import com.democracy.person.publisher.ChallengeEventPub;
import java.util.ArrayList;
import java.util.List;
import javax.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ChallengeServiceImpl implements ChallengeService {

    // @Autowired
    //private UserMapper userMapper;

    //@Autowired
    //private ChallengeAttemptMapper challengeAttemptMapper;

    @Autowired
    private ChallengeEventPub challengeEventPub;

    @Transactional
    @Override
    public ChallengeAttempt verifyAttempt(ChallengeAttemptDTO attemptDTO) {
        // Check if the user already exists for that alias, otherwise create it
        User userParam = new User();
        userParam.setAlias(attemptDTO.getUserAlias());
        userParam.setId(attemptDTO.getId());
        /*
        User user = userMapper
            .select(userParam)
            .orElseGet(() -> {
                return userMapper.insert(new User(attemptDTO.getUserAlias()));
            });
        */
        // Check if the attempt is correct
        boolean isCorrect = attemptDTO.getGuess() == attemptDTO.getFactorA() * attemptDTO.getFactorB();

        // Builds the domain object. Null id since it'll be generated by the DB.
        ChallengeAttempt checkedAttempt = new ChallengeAttempt(
            userParam,
            attemptDTO.getFactorA(),
            attemptDTO.getFactorB(),
            attemptDTO.getGuess(),
            isCorrect
        );

        // Stores the attempt
        //ChallengeAttempt storedAttempt = challengeAttemptMapper.insert(checkedAttempt);

        // Publishes an event to notify potentially interested subscribers
        challengeEventPub.challengeSolved(checkedAttempt);

        return checkedAttempt;
    }

    @Override
    public List<ChallengeAttempt> getStatsForUser(final String userAlias) {
        User user = new User();
        user.setAlias(userAlias);
        ChallengeAttempt challengeAttempt = new ChallengeAttempt();
        challengeAttempt.setUser(user);
        List<ChallengeAttempt> challengeList = new ArrayList<>();
        challengeList.add(challengeAttempt);
        return challengeList; //challengeAttemptMapper.select(challengeAttempt);
    }
}
